-- AlterTable
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "gachaFreeDayKey" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "gachaFreeStandardUsed" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "gachaFreePremiumUsed" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "gachaFreeStandardCooldownAt" TIMESTAMP(3);
